site_name: Intro to Python with Telgeram Bots
theme:
    name: 'material'
markdown_extensions:
    - footnotes
pages:
    - Set-Up: index.md
    - Basics:
        - 1. Data Types, Operations, and Variables: 01-basics.md
        - 2. Data Structures: 02-basics.md
        - 3. Control Flow: 03-basics.md
        - 4. Loops: 04-basics.md
        - 5. Functions: 05-basics.md
    - Bot:
        - 6. Installing Packages: 06-bot.md
        - 7. Sending Messages: 07-bot.md
        - 8. Reacting to Messages: 08-bot.md
        - 9. Sending Commands: 09-bot.md
    - Bonus:
        - 10. How to Google: 10-bonus.md
