site_name: Intro to Python with Telgeram Bots
site_url: https://usp-python.github.io/
repo_url: https://github.com/USP-Python/USP-Python.github.io
google_analytics: ['UA-113561366-1', 'usp-python.github.io']
theme:
    name: 'material'
markdown_extensions:
    - footnotes
extra_css:
    - css/style.css
extra_javascript: 
    - js/jquery-3.3.1.min.js
    - js/lib.js
pages:
    - Set-Up: index.md
    - Basics:
        - 1. Data Types, Operations, and Variables: 01-basics.md
        - 2. Data Structures: 02-basics.md
        - 3. Control Flow: 03-basics.md
        - 4. Functions: 04-basics.md
    - Bot:
        - 5. Installing Packages: 05-bot.md
        - 6. Sending Messages: 06-bot.md
        - 7. Reacting to Commands: 07-bot.md
        - 8. Reacting to Messages: 08-bot.md
    - Bonus:
        - 9. How to Google: 09-bonus.md
